### ISSUE TITLE
Q: howto keepalive on server side

### ISSUE THREAD

**Issue by zhaozg** [indutny/uv_http_t#1]
please show me a example

**Comment by indutny** [comment]
You might want to use [uv_http_req_respond](https://github.com/indutny/uv_http_t/blob/b2f255dbbfa967b3bdaee931baab7ced559e1df4/include/uv_http_t.h#L108-L113) to set appropriate headers. There a couple of examples in the tests: https://github.com/indutny/uv_http_t/blob/master/test/src/test-req-respond.c#L36-L44

However, you should also note that I haven't updated this project in 3 years. It doesn't use the latest libuv and the http_parser, so the things are likely both outdated and have security vulnerabilities.
